sudo: required
services:
  - docker

before_install:
  - docker build -t sgryt87/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sgryt87/react-test npm test -- --coverage

after_success:
  - docker build -t sgryt87/multi-client ./client
  - docker build -t sgryt87/multi-nginx ./nginx
  - docker build -t sgryt87/multi-server ./server
  - docker build -t sgryt87/multi-worker ./worker
  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # pushing these images to dockerhub
  - docker push sgryt87/multi-client
  - docker push sgryt87/multi-ngnix
  - docker push sgryt87/multi-server
  - docker push sgryt87/multi-worker